services:
  devcontainer:
    container_name: ${CONTAINER_NAME}
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        DEBIAN_FRONTEND: noninteractive
        TZ: ${TZ}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
        PYTHON_VERSION: ${PYTHON_VERSION}
        SSHD_PORT: ${SSHD_PORT}
        START_SSHD: ${START_SSHD}
        DEVUSER_PASSWORD: ${DEVUSER_PASSWORD}
    hostname: ${CONTAINER_NAME}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${TARGET_DIR}:/workspaces:cached"
      - "${HOME}/.vscode-server:/home/devuser/.vscode-server"
      - "${HOME}/.gitconfig:/home/devuser/.gitconfig"
      - "${HOME}/.config/gcloud:/home/devuser/.config/gcloud"
      - "${HOME}/.ssh:/home/devuser/.ssh"
    # network_mode: host
    env_file:
      - .env
    ports:
     - "60003:${SSHD_PORT}"